name: my_quotes
description: "A flutter app to save memorable quotes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  basics: ^0.10.0
  drift: ^2.18.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^14.1.0
  intl: 0.19.0
  multiple_search_selection: ^2.6.4
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  safe_url_check: ^1.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer_pro: ^0.0.6
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.21
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  drift_dev: ^2.18.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
