name: my_quotes
description: "A flutter app to save memorable quotes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  basics: ^0.10.0
  characters: ^1.3.0
  crypto: ^3.0.5
  diacritic: ^0.1.5
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  encrypt: ^5.0.3
  envied: ^0.5.4
  feedback_sentry: ^3.0.1
  file_picker: ^8.1.2
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  fuzzywuzzy: ^1.2.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  multiple_search_selection: ^2.7.0
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  screenshot: ^3.0.0
  sentry: ^8.9.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  timeago: ^3.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  dart_code_linter: ^1.1.3
  drift_dev: ^2.20.3
  english_words: ^4.0.0
  envied_generator: ^0.5.4
  faker: ^2.2.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mocktail: ^1.0.4

flutter:
  assets:
    - .env
  uses-material-design: true
  generate: true

