name: my_quotes
description: "A flutter app to save memorable quotes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  basics: ^0.10.0
  cryptography: ^2.7.0
  diacritic: ^0.1.5
  drift: ^2.18.0
  envied: ^0.5.4+1
  feedback_sentry: ^3.0.1
  file_picker: ^8.0.5
  file_saver: ^0.2.13
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^10.0.1
  fuzzywuzzy: ^1.1.6
  get_it: ^7.7.0
  go_router: ^14.1.0
  multiple_search_selection: ^2.6.4
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  screenshot: ^3.0.0
  sentry: ^8.3.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.2
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.21
  timeago: ^3.6.1
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.12
  dart_code_linter: ^1.1.3
  english_words: ^4.0.0
  envied_generator: ^0.5.4+1
  faker: ^2.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  assets:
    - .env
  uses-material-design: true
  generate: true

