name: my_quotes
description: "A flutter app to save memorable quotes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  basics: ^0.10.0
  characters: ^1.3.0
  crypto: ^3.0.5
  diacritic: ^0.1.6
  drift: ^2.20.3
  encrypt: ^5.0.3
  envied: ^0.5.4
  feedback_sentry: ^3.0.1
  file_picker: ^8.1.2
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  fuzzywuzzy: ^1.2.0
  get_it: ^8.0.0
  go_router: ^14.3.0
  multiple_search_selection: ^2.7.0
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  screenshot: ^3.0.0
  sentry: ^8.9.0
  share_plus: ^10.0.3
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.4.6
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  english_words: ^4.0.0
  envied_generator: ^0.5.4
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - .env
    - assets/data_usage_message/data_usage_en.yaml
    - assets/data_usage_message/data_usage_pt.yaml
  uses-material-design: true
  generate: true

